# Generated by Django 3.2.13 on 2025-12-18 08:33

import api_automation.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='集合名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='集合描述')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': 'API集合',
                'verbose_name_plural': 'API集合',
                'db_table': 'api_collections',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ApiProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='项目描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_projects', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': 'API项目',
                'verbose_name_plural': 'API项目',
                'db_table': 'api_projects',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ApiTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='用例名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='用例描述')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10, verbose_name='请求方法')),
                ('url', models.TextField(verbose_name='接口地址')),
                ('headers', api_automation.models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('params', api_automation.models.JSONField(blank=True, default=dict, verbose_name='请求参数')),
                ('body', api_automation.models.JSONField(blank=True, default=dict, verbose_name='请求体')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to='api_automation.apicollection', verbose_name='所属集合')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='api_automation.apiproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'API测试用例',
                'verbose_name_plural': 'API测试用例',
                'db_table': 'api_test_cases',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddField(
            model_name='apicollection',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_collections', to='api_automation.apiproject', verbose_name='所属项目'),
        ),
    ]
