# Generated by Django 3.2.13 on 2025-12-19 06:57

import api_automation.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_automation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTestEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='环境名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='环境描述')),
                ('base_url', models.URLField(verbose_name='基础URL')),
                ('global_headers', api_automation.models.JSONField(blank=True, default=dict, verbose_name='全局请求头')),
                ('global_variables', api_automation.models.JSONField(blank=True, default=dict, verbose_name='全局变量')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认环境')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_environments', to='api_automation.apiproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'API测试环境',
                'verbose_name_plural': 'API测试环境',
                'db_table': 'api_test_environments',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ApiTestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='执行名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='执行描述')),
                ('test_cases', api_automation.models.JSONField(default=list, verbose_name='测试用例ID列表')),
                ('status', models.CharField(choices=[('PENDING', '待执行'), ('RUNNING', '执行中'), ('COMPLETED', '已完成'), ('FAILED', '执行失败'), ('CANCELLED', '已取消')], default='PENDING', max_length=20, verbose_name='执行状态')),
                ('total_count', models.IntegerField(default=0, verbose_name='总用例数')),
                ('passed_count', models.IntegerField(default=0, verbose_name='通过数')),
                ('failed_count', models.IntegerField(default=0, verbose_name='失败数')),
                ('skipped_count', models.IntegerField(default=0, verbose_name='跳过数')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='执行时长(秒)')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_executions', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_executions', to='api_automation.apitestenvironment', verbose_name='执行环境')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_executions', to='api_automation.apiproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'API测试执行',
                'verbose_name_plural': 'API测试执行',
                'db_table': 'api_test_executions',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ApiTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PASSED', '通过'), ('FAILED', '失败'), ('SKIPPED', '跳过'), ('ERROR', '错误')], max_length=20, verbose_name='测试状态')),
                ('response_status', models.IntegerField(blank=True, null=True, verbose_name='响应状态码')),
                ('response_time', models.IntegerField(blank=True, null=True, verbose_name='响应时间(ms)')),
                ('response_size', models.IntegerField(blank=True, null=True, verbose_name='响应大小(bytes)')),
                ('request_url', models.TextField(blank=True, null=True, verbose_name='请求URL')),
                ('request_method', models.CharField(blank=True, max_length=10, null=True, verbose_name='请求方法')),
                ('request_headers', api_automation.models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('request_body', api_automation.models.JSONField(blank=True, default=dict, verbose_name='请求体')),
                ('response_headers', api_automation.models.JSONField(blank=True, default=dict, verbose_name='响应头')),
                ('response_body', api_automation.models.JSONField(blank=True, default=dict, verbose_name='响应体')),
                ('assertion_results', api_automation.models.JSONField(blank=True, default=list, verbose_name='断言结果')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='执行时长(ms)')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='api_automation.apitestexecution', verbose_name='执行记录')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='api_automation.apitestcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': 'API测试结果',
                'verbose_name_plural': 'API测试结果',
                'db_table': 'api_test_results',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ApiTestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='报告名称')),
                ('summary', api_automation.models.JSONField(default=dict, verbose_name='执行摘要')),
                ('test_results', api_automation.models.JSONField(default=list, verbose_name='测试结果详情')),
                ('charts_data', api_automation.models.JSONField(default=dict, verbose_name='图表数据')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='api_automation.apitestexecution', verbose_name='执行记录')),
            ],
            options={
                'verbose_name': 'API测试报告',
                'verbose_name_plural': 'API测试报告',
                'db_table': 'api_test_reports',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ApiDataDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='数据源名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='数据源描述')),
                ('data_type', models.CharField(choices=[('JSON', 'JSON数据'), ('CSV', 'CSV文件'), ('EXCEL', 'Excel文件'), ('DATABASE', '数据库')], default='JSON', max_length=20, verbose_name='数据类型')),
                ('data_source', api_automation.models.JSONField(default=dict, verbose_name='数据源配置')),
                ('data_content', api_automation.models.JSONField(default=list, verbose_name='数据内容')),
                ('variable_mapping', api_automation.models.JSONField(default=dict, verbose_name='变量映射')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_drivers', to='api_automation.apiproject', verbose_name='所属项目')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_drivers', to='api_automation.apitestcase', verbose_name='关联测试用例')),
            ],
            options={
                'verbose_name': 'API数据驱动',
                'verbose_name_plural': 'API数据驱动',
                'db_table': 'api_data_drivers',
                'ordering': ['-created_time'],
            },
        ),
    ]
