# Generated by Django 3.2.13 on 2025-12-19 07:54

import api_automation.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_automation', '0002_apidatadriver_apitestenvironment_apitestexecution_apitestreport_apitestresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitestcase',
            name='tests',
            field=api_automation.models.JSONField(blank=True, default=list, verbose_name='断言配置'),
        ),
    ]
