# Generated by Django 3.2.13 on 2025-12-23 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_automation', '0003_add_tests_field_to_testcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTestCaseExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(help_text='变量名，用于在后续请求中引用', max_length=100, verbose_name='变量名')),
                ('extract_type', models.CharField(choices=[('regex', '正则表达式'), ('json_path', 'JSON路径'), ('xpath', 'XPath表达式'), ('css_selector', 'CSS选择器'), ('header', 'Header解析'), ('cookie', 'Cookie解析')], max_length=20, verbose_name='提取类型')),
                ('extract_expression', models.TextField(help_text='根据提取类型，填写相应的表达式', verbose_name='提取表达式')),
                ('default_value', models.TextField(blank=True, help_text='提取失败时使用的默认值', null=True, verbose_name='默认值')),
                ('extract_scope', models.CharField(choices=[('body', '响应体'), ('headers', '响应头'), ('url', 'URL')], default='body', max_length=20, verbose_name='提取范围')),
                ('variable_scope', models.CharField(choices=[('local', '局部变量'), ('global', '全局变量')], default='local', max_length=20, verbose_name='变量作用域')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractions', to='api_automation.apitestcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '测试用例数据提取',
                'verbose_name_plural': '测试用例数据提取',
                'db_table': 'api_test_case_extractions',
                'ordering': ['created_time'],
            },
        ),
        migrations.CreateModel(
            name='ApiTestCaseAssertion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assertion_type', models.CharField(choices=[('status_code', 'HTTP状态码'), ('response_time', '响应时间'), ('response_body', '响应体'), ('response_headers', '响应头'), ('json_value', 'JSON值'), ('text_contains', '文本包含'), ('json_schema', 'JSON Schema')], max_length=20, verbose_name='断言类型')),
                ('target', models.CharField(blank=True, help_text='如: status_code, headers.content-type, $.data.id', max_length=500, null=True, verbose_name='目标字段')),
                ('operator', models.CharField(choices=[('equals', '等于'), ('not_equals', '不等于'), ('contains', '包含'), ('not_contains', '不包含'), ('less_than', '小于'), ('less_than_equal', '小于等于'), ('greater_than', '大于'), ('greater_than_equal', '大于等于'), ('regex', '正则匹配'), ('json_path', 'JSON路径'), ('is_empty', '为空'), ('is_not_empty', '不为空'), ('range', '范围'), ('valid', '有效'), ('invalid', '无效')], max_length=20, verbose_name='操作符')),
                ('expected_value', models.TextField(blank=True, null=True, verbose_name='期望值')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.IntegerField(default=0, verbose_name='执行顺序')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assertions', to='api_automation.apitestcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '测试用例断言',
                'verbose_name_plural': '测试用例断言',
                'db_table': 'api_test_case_assertions',
                'ordering': ['order', 'created_time'],
            },
        ),
    ]
