# Generated by Django 3.2.13 on 2025-12-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_automation', '0004_apitestcaseassertion_apitestcaseextraction'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='apicollection',
            index=models.Index(fields=['project', 'is_deleted'], name='collection_project_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='apicollection',
            index=models.Index(fields=['project', 'name'], name='collection_project_name_idx'),
        ),
        migrations.AddIndex(
            model_name='apicollection',
            index=models.Index(fields=['created_time'], name='collection_created_idx'),
        ),
        migrations.AddIndex(
            model_name='apiproject',
            index=models.Index(fields=['owner', 'is_deleted'], name='project_owner_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='apiproject',
            index=models.Index(fields=['created_time'], name='project_created_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestcase',
            index=models.Index(fields=['collection', 'is_deleted'], name='case_collection_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestcase',
            index=models.Index(fields=['project', 'is_deleted'], name='case_project_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestcase',
            index=models.Index(fields=['created_time'], name='case_created_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestenvironment',
            index=models.Index(fields=['project', 'is_deleted'], name='env_project_deleted_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestenvironment',
            index=models.Index(fields=['project', 'is_default'], name='env_project_default_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestexecution',
            index=models.Index(fields=['project', 'created_time'], name='exec_project_created_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestexecution',
            index=models.Index(fields=['environment', 'status'], name='exec_env_status_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestexecution',
            index=models.Index(fields=['status', 'created_time'], name='exec_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestresult',
            index=models.Index(fields=['execution', 'status'], name='result_exec_status_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestresult',
            index=models.Index(fields=['test_case', 'start_time'], name='result_case_time_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestresult',
            index=models.Index(fields=['status', 'start_time'], name='result_status_time_idx'),
        ),
    ]
