# Generated by Django 3.2.13 on 2025-12-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_automation', '0005_auto_20251226_1038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apitestenvironment',
            options={'ordering': ['-is_favorite', '-created_time'], 'verbose_name': 'API测试环境', 'verbose_name_plural': 'API测试环境'},
        ),
        migrations.AddField(
            model_name='apitestenvironment',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='是否收藏'),
        ),
        migrations.AddIndex(
            model_name='apitestenvironment',
            index=models.Index(fields=['is_favorite'], name='env_favorite_idx'),
        ),
    ]
