# Generated by Django 3.2.13 on 2025-12-30 06:54

import api_automation.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_automation', '0006_auto_20251230_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitestcase',
            name='input_variables',
            field=api_automation.models.JSONField(blank=True, default=dict, help_text='定义从前置用例或环境中获取的输入变量', verbose_name='输入变量定义'),
        ),
        migrations.AddField(
            model_name='apitestcase',
            name='output_variables',
            field=api_automation.models.JSONField(blank=True, default=dict, help_text='定义从响应中提取的输出变量，供后续用例使用', verbose_name='输出变量定义'),
        ),
        migrations.CreateModel(
            name='ApiHttpExecutionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('request_url', models.TextField(verbose_name='完整请求URL')),
                ('request_base_url', models.TextField(verbose_name='基础URL')),
                ('request_path', models.TextField(verbose_name='请求路径')),
                ('request_headers', api_automation.models.JSONField(default=dict, verbose_name='请求头')),
                ('request_params', api_automation.models.JSONField(default=dict, verbose_name='Query参数')),
                ('request_body', api_automation.models.JSONField(blank=True, default=dict, verbose_name='请求体')),
                ('request_body_type', models.CharField(choices=[('JSON', 'JSON'), ('FORM', '表单'), ('RAW', '原始'), ('NONE', '无')], default='NONE', max_length=20, verbose_name='请求体类型')),
                ('request_size', models.IntegerField(blank=True, null=True, verbose_name='请求大小(bytes)')),
                ('response_status', models.IntegerField(blank=True, null=True, verbose_name='响应状态码')),
                ('response_status_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='响应状态文本')),
                ('response_headers', api_automation.models.JSONField(blank=True, default=dict, verbose_name='响应头')),
                ('response_body', api_automation.models.JSONField(blank=True, default=dict, verbose_name='响应体')),
                ('response_body_text', models.TextField(blank=True, null=True, verbose_name='响应体原文(非JSON)')),
                ('response_size', models.IntegerField(blank=True, null=True, verbose_name='响应大小(bytes)')),
                ('response_encoding', models.CharField(blank=True, max_length=50, null=True, verbose_name='响应编码')),
                ('request_time', models.DateTimeField(verbose_name='请求发送时间')),
                ('response_time', models.DateTimeField(blank=True, null=True, verbose_name='响应接收时间')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='响应时间(ms)')),
                ('status', models.CharField(choices=[('SUCCESS', '成功'), ('FAILED', '失败'), ('TIMEOUT', '超时'), ('ERROR', '错误')], default='ERROR', max_length=20, verbose_name='执行状态')),
                ('error_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='错误类型')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('stack_trace', models.TextField(blank=True, null=True, verbose_name='错误堆栈')),
                ('assertion_results', api_automation.models.JSONField(blank=True, default=list, verbose_name='断言结果列表')),
                ('assertions_passed', models.IntegerField(default=0, verbose_name='断言通过数')),
                ('assertions_failed', models.IntegerField(default=0, verbose_name='断言失败数')),
                ('extraction_results', api_automation.models.JSONField(blank=True, default=dict, verbose_name='数据提取结果')),
                ('extracted_variables', api_automation.models.JSONField(blank=True, default=dict, verbose_name='提取的变量')),
                ('environment_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='环境名称')),
                ('execution_source', models.CharField(choices=[('MANUAL', '手动执行'), ('BATCH', '批量执行'), ('SCHEDULED', '定时执行'), ('API', 'API触发')], default='MANUAL', max_length=20, verbose_name='执行来源')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='是否收藏')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('environment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='http_records', to='api_automation.apitestenvironment', verbose_name='执行环境')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='http_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行者')),
                ('execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='http_records', to='api_automation.apitestexecution', verbose_name='执行批次')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='http_execution_records', to='api_automation.apiproject', verbose_name='所属项目')),
                ('test_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execution_records', to='api_automation.apitestcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': 'HTTP接口执行记录',
                'verbose_name_plural': 'HTTP接口执行记录',
                'db_table': 'api_http_execution_records',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddIndex(
            model_name='apihttpexecutionrecord',
            index=models.Index(fields=['test_case', 'created_time'], name='record_case_time_idx'),
        ),
        migrations.AddIndex(
            model_name='apihttpexecutionrecord',
            index=models.Index(fields=['execution', 'created_time'], name='record_exec_time_idx'),
        ),
        migrations.AddIndex(
            model_name='apihttpexecutionrecord',
            index=models.Index(fields=['project', 'created_time'], name='record_project_time_idx'),
        ),
        migrations.AddIndex(
            model_name='apihttpexecutionrecord',
            index=models.Index(fields=['status', 'created_time'], name='record_status_time_idx'),
        ),
        migrations.AddIndex(
            model_name='apihttpexecutionrecord',
            index=models.Index(fields=['environment', 'created_time'], name='record_env_time_idx'),
        ),
        migrations.AddIndex(
            model_name='apihttpexecutionrecord',
            index=models.Index(fields=['is_favorite', 'created_time'], name='record_favorite_time_idx'),
        ),
        migrations.AddIndex(
            model_name='apihttpexecutionrecord',
            index=models.Index(fields=['executed_by', 'created_time'], name='record_user_time_idx'),
        ),
    ]
