# Generated by Django 3.2.13 on 2026-01-04 03:59

import api_automation.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_automation', '0007_auto_20251230_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitestresult',
            name='error_info',
            field=api_automation.models.JSONField(blank=True, default=dict, help_text='存储错误类型、堆栈、断言失败详情等', verbose_name='错误详情'),
        ),
        migrations.AddField(
            model_name='apitestresult',
            name='extracted_variables',
            field=api_automation.models.JSONField(blank=True, default=dict, help_text='存储从响应中提取的变量，供后续用例使用', verbose_name='提取的变量'),
        ),
        migrations.AddField(
            model_name='apitestresult',
            name='request_full',
            field=api_automation.models.JSONField(blank=True, default=dict, help_text='HTTP非200时存储：完整headers、body、params等', verbose_name='完整请求信息'),
        ),
        migrations.AddField(
            model_name='apitestresult',
            name='request_summary',
            field=api_automation.models.JSONField(blank=True, default=dict, help_text='HTTP 200时存储：method, url, 关键headers', verbose_name='请求摘要'),
        ),
        migrations.AddField(
            model_name='apitestresult',
            name='response_full',
            field=api_automation.models.JSONField(blank=True, default=dict, help_text='HTTP非200时存储：完整headers、body、error_stack等', verbose_name='完整响应信息'),
        ),
        migrations.AddField(
            model_name='apitestresult',
            name='response_summary',
            field=api_automation.models.JSONField(blank=True, default=dict, help_text='HTTP 200时存储：status_code, response_time, content_length', verbose_name='响应摘要'),
        ),
        migrations.AlterField(
            model_name='apitestresult',
            name='request_body',
            field=api_automation.models.JSONField(blank=True, default=dict, verbose_name='请求体（兼容）'),
        ),
        migrations.AlterField(
            model_name='apitestresult',
            name='request_headers',
            field=api_automation.models.JSONField(blank=True, default=dict, verbose_name='请求头（兼容）'),
        ),
        migrations.AlterField(
            model_name='apitestresult',
            name='response_body',
            field=api_automation.models.JSONField(blank=True, default=dict, verbose_name='响应体（兼容）'),
        ),
        migrations.AlterField(
            model_name='apitestresult',
            name='response_headers',
            field=api_automation.models.JSONField(blank=True, default=dict, verbose_name='响应头（兼容）'),
        ),
    ]
