# Generated by Django 3.2.13 on 2026-01-04 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_automation', '0008_auto_20260104_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicollection',
            name='module',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所属模块'),
        ),
        migrations.AddField(
            model_name='apicollection',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddField(
            model_name='apitestcase',
            name='module',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所属模块'),
        ),
        migrations.AddField(
            model_name='apitestcase',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to=settings.AUTH_USER_MODEL, verbose_name='负责人'),
        ),
        migrations.AddIndex(
            model_name='apicollection',
            index=models.Index(fields=['owner'], name='collection_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='apicollection',
            index=models.Index(fields=['module'], name='collection_module_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestcase',
            index=models.Index(fields=['owner'], name='case_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='apitestcase',
            index=models.Index(fields=['module'], name='case_module_idx'),
        ),
    ]
