# Generated by Django 6.0.1 on 2026-03-03 06:09

import api_automation.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_automation', '0009_auto_20260104_1406'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiGeneratedArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('TRAFFIC', '流量录制'), ('RAG', '文档生成')], max_length=20, verbose_name='来源类型')),
                ('source_id', models.IntegerField(verbose_name='来源ID')),
                ('artifact_type', models.CharField(choices=[('TEST_CASE', '单接口用例'), ('SCENARIO', '场景用例')], max_length=20, verbose_name='产物类型')),
                ('name', models.CharField(max_length=200, verbose_name='名称')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('READY', '可提交'), ('COMMITTED', '已提交'), ('FAILED', '失败')], default='DRAFT', max_length=20)),
                ('payload', api_automation.models.JSONField(blank=True, default=dict, verbose_name='产物内容')),
                ('preview_diff', api_automation.models.JSONField(blank=True, default=dict, verbose_name='预览差异')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_artifacts', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_artifacts', to='api_automation.apiproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'API生成产物',
                'verbose_name_plural': 'API生成产物',
                'db_table': 'api_generated_artifacts',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ApiTestScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='场景名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='场景描述')),
                ('steps', api_automation.models.JSONField(blank=True, default=list, verbose_name='场景步骤')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('ACTIVE', '启用'), ('DISABLED', '禁用')], default='DRAFT', max_length=20, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_scenarios', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_scenarios', to='api_automation.apiproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'API场景用例',
                'verbose_name_plural': 'API场景用例',
                'db_table': 'api_test_scenarios',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ApiTrafficCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='录制名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='录制描述')),
                ('capture_type', models.CharField(choices=[('PROXY_UPLOAD', '代理上传'), ('PROXY_LIVE', '代理实时')], default='PROXY_UPLOAD', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='文件路径')),
                ('file_format', models.CharField(default='JSON', max_length=20, verbose_name='文件格式')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='文件大小')),
                ('content_hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='文件哈希')),
                ('status', models.CharField(choices=[('UPLOADED', '已上传'), ('PARSING', '解析中'), ('PARSED', '已解析'), ('FAILED', '解析失败')], default='UPLOADED', max_length=20)),
                ('total_entries', models.IntegerField(default=0, verbose_name='原始条目数')),
                ('filtered_entries', models.IntegerField(default=0, verbose_name='过滤后条目数')),
                ('sessions_count', models.IntegerField(default=0, verbose_name='会话数')),
                ('error_info', api_automation.models.JSONField(blank=True, default=dict, verbose_name='错误信息')),
                ('processing_config', api_automation.models.JSONField(blank=True, default=dict, verbose_name='处理配置')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traffic_captures', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_captures', to='api_automation.apiproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'API流量录制',
                'verbose_name_plural': 'API流量录制',
                'db_table': 'api_traffic_captures',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ApiTrafficSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=128, verbose_name='会话标识')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='持续时间')),
                ('entry_count', models.IntegerField(default=0, verbose_name='条目数量')),
                ('status', models.CharField(choices=[('READY', '可生成'), ('FILTERED', '已过滤'), ('FAILED', '失败')], default='READY', max_length=20)),
                ('tags', api_automation.models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api_automation.apitrafficcapture', verbose_name='录制任务')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_sessions', to='api_automation.apiproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'API流量会话',
                'verbose_name_plural': 'API流量会话',
                'db_table': 'api_traffic_sessions',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ApiTrafficEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('request_url', models.TextField(verbose_name='请求URL')),
                ('request_headers', api_automation.models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('request_params', api_automation.models.JSONField(blank=True, default=dict, verbose_name='请求参数')),
                ('request_body', api_automation.models.JSONField(blank=True, default=dict, verbose_name='请求体')),
                ('response_status', models.IntegerField(blank=True, null=True, verbose_name='响应状态码')),
                ('response_headers', api_automation.models.JSONField(blank=True, default=dict, verbose_name='响应头')),
                ('response_body', api_automation.models.JSONField(blank=True, default=dict, verbose_name='响应体')),
                ('response_time_ms', models.IntegerField(default=0, verbose_name='响应耗时')),
                ('error_info', api_automation.models.JSONField(blank=True, default=dict, verbose_name='错误信息')),
                ('fingerprint', models.CharField(db_index=True, max_length=64, verbose_name='去重指纹')),
                ('is_valuable', models.BooleanField(default=True, verbose_name='是否有效')),
                ('filter_reason', models.CharField(blank=True, max_length=200, verbose_name='过滤原因')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='api_automation.apitrafficsession', verbose_name='所属会话')),
            ],
            options={
                'verbose_name': 'API流量条目',
                'verbose_name_plural': 'API流量条目',
                'db_table': 'api_traffic_entries',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ApiTrafficVariableRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=100, verbose_name='变量名')),
                ('source_type', models.CharField(choices=[('JSONPATH', 'JSONPath'), ('REGEX', 'Regex'), ('HEADER', 'Header')], max_length=20, verbose_name='提取类型')),
                ('expression', models.CharField(max_length=500, verbose_name='表达式')),
                ('target_scope', models.CharField(choices=[('SCENARIO', '场景变量'), ('GLOBAL', '全局变量')], default='SCENARIO', max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_rules', to='api_automation.apitrafficentry', verbose_name='关联条目')),
            ],
            options={
                'verbose_name': 'API流量变量规则',
                'verbose_name_plural': 'API流量变量规则',
                'db_table': 'api_traffic_variable_rules',
                'ordering': ['-created_time'],
            },
        ),
    ]
