# Generated by Django 6.0.1 on 2026-01-20 07:55

import django.db.models.deletion
import ui_automation.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UiTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='测试用例名称', max_length=200, verbose_name='用例名称')),
                ('natural_language_task', models.TextField(help_text='用自然语言描述测试任务，AI将自动理解并执行。例如: 打开首页，点击登录按钮，输入用户名和密码，验证登录成功', verbose_name='自然语言任务描述')),
                ('expected_result', models.TextField(blank=True, help_text='测试的预期结果描述', verbose_name='预期结果')),
                ('tags', models.TextField(blank=True, default='[]', help_text='测试用例标签，用于分类管理', verbose_name='标签')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': 'UI测试用例',
                'verbose_name_plural': 'UI测试用例',
                'db_table': 'ui_test_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UiTestProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='项目名称', max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, help_text='项目描述', verbose_name='项目描述')),
                ('base_url', models.URLField(blank=True, help_text='被测应用的基础URL，例如: https://www.example.com', max_length=500, verbose_name='基础URL')),
                ('default_browser_mode', models.CharField(choices=[('headless', '无头模式'), ('headed', '有头模式')], default='headless', help_text='执行测试时的默认浏览器模式', max_length=20, verbose_name='默认浏览器模式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_projects_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'UI测试项目',
                'verbose_name_plural': 'UI测试项目',
                'db_table': 'ui_test_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UiTestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('passed', '通过'), ('failed', '失败'), ('error', '错误'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='执行状态')),
                ('browser_mode', models.CharField(choices=[('headless', '无头模式'), ('headed', '有头模式')], default='headless', max_length=20, verbose_name='浏览器模式')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='执行时长(秒)')),
                ('final_result', models.TextField(blank=True, verbose_name='最终结果')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ui_executions', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='ui_automation.uitestcase', verbose_name='测试用例')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='ui_automation.uitestproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'UI测试执行',
                'verbose_name_plural': 'UI测试执行',
                'db_table': 'ui_test_executions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='uitestcase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='ui_automation.uitestproject', verbose_name='所属项目'),
        ),
        migrations.CreateModel(
            name='UiTestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_history', models.TextField(blank=True, help_text='browser_use Agent 的完整执行步骤历史', null=True, verbose_name='Agent执行历史')),
                ('total_steps', models.IntegerField(default=0, verbose_name='总步骤数')),
                ('completed_steps', models.IntegerField(default=0, verbose_name='已完成步骤数')),
                ('failed_steps', models.IntegerField(default=0, verbose_name='失败步骤数')),
                ('screenshot_paths', models.TextField(blank=True, default='[]', help_text='执行过程中产生的截图文件路径', verbose_name='截图路径列表')),
                ('report_file', models.FileField(blank=True, help_text='生成的HTML格式测试报告文件', null=True, upload_to=ui_automation.models.get_report_upload_path, verbose_name='报告文件')),
                ('summary', models.TextField(blank=True, verbose_name='报告摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('execution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='ui_automation.uitestexecution', verbose_name='执行记录')),
            ],
            options={
                'verbose_name': 'UI测试报告',
                'verbose_name_plural': 'UI测试报告',
                'db_table': 'ui_test_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UiScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to=ui_automation.models.get_screenshot_upload_path, verbose_name='截图文件')),
                ('description', models.CharField(blank=True, help_text='截图对应的操作步骤描述', max_length=500, verbose_name='截图描述')),
                ('step_number', models.IntegerField(verbose_name='步骤序号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='ui_automation.uitestexecution', verbose_name='执行记录')),
            ],
            options={
                'verbose_name': 'UI测试截图',
                'verbose_name_plural': 'UI测试截图',
                'db_table': 'ui_screenshots',
                'ordering': ['execution', 'step_number'],
                'indexes': [models.Index(fields=['execution', 'step_number'], name='ui_screensh_executi_7bcca1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='uitestproject',
            index=models.Index(fields=['-created_at'], name='ui_test_pro_created_4e3002_idx'),
        ),
        migrations.AddIndex(
            model_name='uitestproject',
            index=models.Index(fields=['created_by'], name='ui_test_pro_created_fa19fd_idx'),
        ),
        migrations.AddIndex(
            model_name='uitestproject',
            index=models.Index(fields=['is_deleted'], name='ui_test_pro_is_dele_86a8f6_idx'),
        ),
        migrations.AddIndex(
            model_name='uitestexecution',
            index=models.Index(fields=['-created_at'], name='ui_test_exe_created_598c80_idx'),
        ),
        migrations.AddIndex(
            model_name='uitestexecution',
            index=models.Index(fields=['project'], name='ui_test_exe_project_d663fc_idx'),
        ),
        migrations.AddIndex(
            model_name='uitestexecution',
            index=models.Index(fields=['test_case'], name='ui_test_exe_test_ca_630326_idx'),
        ),
        migrations.AddIndex(
            model_name='uitestexecution',
            index=models.Index(fields=['status'], name='ui_test_exe_status_68ba49_idx'),
        ),
        migrations.AddIndex(
            model_name='uitestexecution',
            index=models.Index(fields=['-started_at'], name='ui_test_exe_started_bfe374_idx'),
        ),
        migrations.AddIndex(
            model_name='uitestcase',
            index=models.Index(fields=['-created_at'], name='ui_test_cas_created_5f87b9_idx'),
        ),
        migrations.AddIndex(
            model_name='uitestcase',
            index=models.Index(fields=['project'], name='ui_test_cas_project_155d24_idx'),
        ),
        migrations.AddIndex(
            model_name='uitestcase',
            index=models.Index(fields=['priority'], name='ui_test_cas_priorit_c5ae9c_idx'),
        ),
        migrations.AddIndex(
            model_name='uitestcase',
            index=models.Index(fields=['is_enabled'], name='ui_test_cas_is_enab_7aab2a_idx'),
        ),
        migrations.AddIndex(
            model_name='uitestcase',
            index=models.Index(fields=['is_deleted'], name='ui_test_cas_is_dele_7b1837_idx'),
        ),
        migrations.AddIndex(
            model_name='uitestreport',
            index=models.Index(fields=['-created_at'], name='ui_test_rep_created_6da5b5_idx'),
        ),
        migrations.AddIndex(
            model_name='uitestreport',
            index=models.Index(fields=['execution'], name='ui_test_rep_executi_c49501_idx'),
        ),
    ]
