# Generated by Django 6.0.1 on 2026-01-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uitestcase',
            name='browser_mode',
            field=models.CharField(choices=[('headless', '无头模式'), ('headed', '有头模式')], default='headless', help_text='执行此用例时的浏览器模式', max_length=20, verbose_name='浏览器模式'),
        ),
        migrations.AddField(
            model_name='uitestcase',
            name='description',
            field=models.TextField(blank=True, help_text='测试用例的详细描述', verbose_name='用例描述'),
        ),
        migrations.AddField(
            model_name='uitestcase',
            name='retry_count',
            field=models.IntegerField(default=0, help_text='失败后的重试次数', verbose_name='重试次数'),
        ),
        migrations.AddField(
            model_name='uitestcase',
            name='timeout',
            field=models.IntegerField(default=120, help_text='单步操作的超时时间', verbose_name='超时时间(秒)'),
        ),
    ]
