# Generated by Django 3.2.13 on 2026-01-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0002_uitestcase_browser_mode_uitestcase_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uitestreport',
            name='json_report_path',
            field=models.CharField(blank=True, help_text='browser-use Agent 生成的 JSON 格式执行报告文件路径', max_length=500, null=True, verbose_name='JSON报告路径'),
        ),
    ]
